version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - curl -sSL https://install.python-poetry.org | python3 -
      - poetry config virtualenvs.create false
      - poetry install

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - method: pip
      path: .
