#!/usr/bin/bash

root=$(realpath $(dirname $0))

if [[ ${1,,} == "a"* ]]; then
  cd $root/yadism
  git checkout master
  cd $root/pineko
  git checkout main
elif [[ ${1,,} == "n"* ]]; then
  cd $root/yadism
  git checkout numerical_fonll
  cd $root/pineko
  git checkout num_fonll
elif [[ ${1,,} == "f"* ]]; then
  cd $root/yadism
  git checkout fix_numerical_fonll
  cd $root/pineko
  git checkout num_fonll
else
  cat <<EOL
Supported options are
  - [n]umerical
  - [f]ixed (patched) numerical
  - [a]nalitycal

(only the first letter is actually matched)
EOL
fi
