#!/usr/bin/bash

if [ -z "$1" ]; then
  echo "An argument is required, to specify the root folder where to bootstrap."
  exit
fi

root=$(realpath $1)
# temp dir, to download file and similar
mkdir -p $root/tmp

# copy/update assets
# ------------------
echo "Copying assets..."
bootdir=$(dirname $(realpath $0))
cp -r $bootdir/assets/* $root
sed -i "s@\$bootdir@$bootdir@" $root/activate
sed -i "s@\$root@$root@" $root/activate

# create environment and install deps
# -----------------------------------
environ=$root/env
if [ ! -d $environ ]; then
  echo "Creating environment..."
  virtualenv $environ
  . $environ/bin/activate
  pip install pineline[full]
  # more development tools
  pip install ipython pdbpp
  deactivate
fi

# replace some dependencies with repos
pushd $root >/dev/null
for proj in "yadism" "pineko" "pinecards"; do
  if [ ! -d $proj ]; then
    git clone https://github.com/NNPDF/$proj
  fi
  pushd $root/$proj >/dev/null
  echo "Pulling $proj..."
  git pull >/dev/null
  # only install in development once
  if [ -f ./pyproject.toml ]; then
    . $environ/bin/activate
    path=$(python -c "import $proj; print($proj.__file__)")
    if [[ $path != $root/$proj* ]]; then
      pip install -e .
    fi
    deactivate
  fi
  popd >/dev/null
done
popd >/dev/null

# install the project itself
. $environ/bin/activate
fonllimport=$(python -c "import fonll" 2>&1 >/dev/null)
if [[ $fonllimport == *"ModuleNotFoundError"* ]]; then
  pip install -e $root
fi
deactivate

# install & configure LHAPDF
# --------------------------
lhaimport=$($environ/bin/python -c "import lhapdf" 2>&1 >/dev/null)
if [[ $lhaimport == *"ModuleNotFoundError"* ]]; then
  echo "Installing LHAPDF..."

  base="https://raw.githubusercontent.com/NNPDF/workflows/v2/packages/lhapdf"
  files=("install.sh" "variables.sh" "download.sh" "clean.sh")

  pushd $root/tmp
  for f in "${files[@]}"; do
    wget $base/$f
  done
  export PREFIX=$environ
  sh install.sh

  sh clean.sh
  for f in "${files[@]}"; do
    rm $f
  done
  popd
fi

# install useful PDF sets
# -----------------------
mkdir -p $root/LHAPDF
pushd $root/LHAPDF >/dev/null
for nf in {3..5}; do
  set="221012-01-rs-nnpdf40_baseline_repeat_nf${nf}"
  if [ ! -d $set ]; then
    echo "Installing PDF set $set..."
    archive="${set}.tar.gz"
    url="https://data.nnpdf.science/pdfs/${archive}"
    wget $url
    tar xzf $archive
    rm $archive
  fi
done
popd >/dev/null

# clean up
# --------
rm -rf $root/tmp
echo "Done!"
